function Rnet_fixed = rotationEuler(thetax,thetay,thetaz)
%ROTATIONEULER
%    RNET_FIXED = ROTATIONEULER(THETAX,THETAY,THETAZ)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    27-Nov-2018 12:56:16

t2 = thetaz.*pi.*(1.0./1.8e2);
t3 = cos(t2);
t4 = thetax.*pi.*(1.0./1.8e2);
t5 = thetay.*pi.*(1.0./1.8e2);
t6 = sin(t4);
t7 = sin(t2);
t8 = cos(t4);
t9 = sin(t5);
t10 = cos(t5);
Rnet_fixed = reshape([t3.*t10,t7.*t10,-t9,-t7.*t8+t3.*t6.*t9,t3.*t8+t6.*t7.*t9,t6.*t10,t6.*t7+t3.*t8.*t9,-t3.*t6+t7.*t8.*t9,t8.*t10],[3,3]);
