function b = fourBar_rhsStuffbVectorDAE(L1,L2,L3,d1,d2,d3,g,m1,m2,m3,theta1,theta2,theta3,theta1dot,theta2dot,theta3dot)
%FOURBAR_RHSSTUFFBVECTORDAE
%    B = FOURBAR_RHSSTUFFBVECTORDAE(L1,L2,L3,D1,D2,D3,G,M1,M2,M3,THETA1,THETA2,THETA3,THETA1DOT,THETA2DOT,THETA3DOT)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    06-Dec-2018 14:02:27

t2 = theta1dot.^2;
t3 = cos(theta1);
t4 = sin(theta1);
t5 = theta2dot.^2;
t6 = cos(theta2);
t7 = sin(theta2);
t8 = theta3dot.^2;
t9 = cos(theta3);
t10 = sin(theta3);
t11 = L3-d3;
b = [-g.*m1;0.0;-g.*m2;0.0;-g.*m3;0.0;0.0;0.0;0.0;-d1.*t2.*t3;-d1.*t2.*t4;-L1.*t2.*t3+d1.*t2.*t3-d2.*t5.*t6;-L1.*t2.*t4+d1.*t2.*t4-d2.*t5.*t7;-L2.*t5.*t6+d2.*t5.*t6-d3.*t8.*t9;-L2.*t5.*t7+d2.*t5.*t7-d3.*t8.*t10;t8.*t9.*t11;t8.*t10.*t11];
