function A = rhsStuffmassMatrixAMB(I1,I2,I3,L1,L2,d1,d2,d3,m1,m2,m3,theta1,theta2,theta3)
%RHSSTUFFMASSMATRIXAMB
%    A = RHSSTUFFMASSMATRIXAMB(I1,I2,I3,L1,L2,D1,D2,D3,M1,M2,M3,THETA1,THETA2,THETA3)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    02-Dec-2018 16:23:52

t2 = L1.^2;
t3 = theta1-theta2;
t4 = cos(t3);
t5 = sin(theta2);
t6 = cos(theta2);
t7 = sin(theta1);
t8 = L1.*t7;
t9 = cos(theta1);
t10 = L1.*t9;
t11 = cos(theta3);
t12 = L2.*t6;
t13 = d3.*t11;
t14 = t10+t12+t13;
t15 = sin(theta3);
t16 = L2.*t5;
t17 = d3.*t15;
t18 = t8+t16+t17;
t19 = theta1-theta3;
t20 = cos(t19);
t21 = theta2-theta3;
t22 = cos(t21);
t23 = d3.^2;
A = reshape([-I1-m2.*t2-m3.*t2-d1.^2.*m1-L1.*L2.*m3.*t4-L1.*d2.*m2.*t4-L1.*d3.*m3.*t20,-L1.*L2.*m3.*t4-L1.*d2.*m2.*t4-L1.*d3.*m3.*t20,-L1.*d3.*m2.*t20,-I2-L2.*m3.*t6.*t14-L2.*m3.*t5.*t18-d2.*m2.*t5.*(t8+d2.*t5)-d2.*m2.*t6.*(t10+d2.*t6),-I2-L2.^2.*m3-d2.^2.*m2-L2.*d3.*m3.*t22,-L2.*d3.*m2.*t22,-I3-d3.*m3.*t11.*t14-d3.*m3.*t15.*t18,-I3-m3.*t23-L2.*d3.*m3.*t22,-I3-m2.*t23],[3,3]);
