function b = rhsStuffbVectorAMB(L1,L2,d1,d2,d3,g,m1,m2,m3,theta1,theta2,theta3,theta1dot,theta2dot,theta3dot)
%RHSSTUFFBVECTORAMB
%    B = RHSSTUFFBVECTORAMB(L1,L2,D1,D2,D3,G,M1,M2,M3,THETA1,THETA2,THETA3,THETA1DOT,THETA2DOT,THETA3DOT)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    02-Dec-2018 16:23:56

t2 = sin(theta1);
t3 = sin(theta2);
t4 = sin(theta3);
t5 = L1.*t2;
t6 = L2.*t3;
t7 = d3.*t4;
t8 = t5+t6+t7;
t9 = theta1dot.^2;
t10 = cos(theta1);
t11 = theta2dot.^2;
t12 = cos(theta2);
t13 = theta3dot.^2;
t14 = cos(theta3);
t15 = L1.*t9.*t10;
t16 = L1.*t2.*t9;
t17 = L1.*t10;
t18 = d2.*t3;
t19 = t5+t18;
t20 = t6+t7;
t21 = L2.*t11.*t12;
t22 = d3.*t13.*t14;
t23 = t15+t21+t22;
t24 = L2.*t12;
t25 = d3.*t14;
t26 = L2.*t3.*t11;
t27 = d3.*t4.*t13;
t28 = t16+t26+t27;
t29 = d2.*t11.*t12;
t30 = t15+t29;
t31 = d2.*t3.*t11;
t32 = t16+t31;
b = [-m2.*t32.*(t17+d2.*t12)+g.*m3.*t8+g.*m2.*t19+m3.*t8.*t23+m2.*t19.*t30-m3.*t28.*(t17+t24+t25)+d1.*g.*m1.*t2;-m3.*t28.*(t24+t25)+g.*m3.*t20+m3.*t20.*t23+d2.*g.*m2.*t3+d2.*m2.*t3.*t30-d2.*m2.*t12.*t32;-d3.*(-g.*m3.*t4+L1.*m2.*t9.*sin(theta1-theta3)+L2.*m2.*t11.*sin(theta2-theta3))];
