function b = rhsStuffbVectorDAE(L1,L2,d1,d2,d3,g,m1,m2,m3,theta1,theta2,theta3,theta1dot,theta2dot,theta3dot)
%RHSSTUFFBVECTORDAE
%    B = RHSSTUFFBVECTORDAE(L1,L2,D1,D2,D3,G,M1,M2,M3,THETA1,THETA2,THETA3,THETA1DOT,THETA2DOT,THETA3DOT)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    06-Dec-2018 04:12:29

t2 = theta1dot.^2;
t3 = cos(theta1);
t4 = sin(theta1);
t5 = theta2dot.^2;
t6 = cos(theta2);
t7 = sin(theta2);
t8 = theta3dot.^2;
b = [-g.*m1;0.0;-g.*m2;0.0;-g.*m3;0.0;0.0;0.0;0.0;-d1.*t2.*t3;-d1.*t2.*t4;-L1.*t2.*t3-d2.*t5.*t6;-L1.*t2.*t4-d2.*t5.*t7;-d3.*t8.*cos(theta3)-L1.*t2.*t3-L2.*t5.*t6;-d3.*t8.*sin(theta3)-L1.*t2.*t4-L2.*t5.*t7];
