function xdoubledot_Lagrange = rhs_Lagrange(c,g,x,xdot)
%RHS_LAGRANGE
%    XDOUBLEDOT_LAGRANGE = RHS_LAGRANGE(C,G,X,XDOT)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    23-Oct-2018 17:07:48

xdoubledot_Lagrange = (c.*x.*(g+c.*xdot.^2.*2.0).*-2.0)./(c.^2.*x.^2.*4.0+1.0);
