function xdoubledot_NE = rhs_NE(c,g,x,xdot)
%RHS_NE
%    XDOUBLEDOT_NE = RHS_NE(C,G,X,XDOT)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    23-Oct-2018 18:45:58

t2 = c.^2;
xdoubledot_NE = -(t2.*x.*xdot.^2.*4.0+c.*g.*x.*2.0)./(t2.*x.^2.*4.0+1.0);
