function q_DAE = rhs_Matrix_DAE(c,g,m,x,xdot,ydot)
%RHS_MATRIX_DAE
%    Q_DAE = RHS_MATRIX_DAE(C,G,M,X,XDOT,YDOT)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    24-Oct-2018 01:19:43

t2 = c.*x.*ydot.*2.0;
t3 = t2+xdot;
t4 = 1.0./t3;
t5 = xdot.^2;
t6 = c.*t5.*2.0;
t7 = g+t6;
q_DAE = [-t4.*t7.*ydot;c.*t4.*(t5.*xdot-g.*x.*ydot).*2.0;m.*t4.*t7.*sign(xdot).*sqrt(t5+ydot.^2)];
