function A = rhsStuffmassMatrixDAE(I1,I2,L1,d1,d2,m1,m2,theta1,theta2)
%RHSSTUFFMASSMATRIXDAE
%    A = RHSSTUFFMASSMATRIXDAE(I1,I2,L1,D1,D2,M1,M2,THETA1,THETA2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    23-Oct-2018 11:50:29

t2 = sin(theta1);
t3 = cos(theta1);
t4 = L1-d1;
t5 = d1.*t2;
t6 = sin(theta2);
t7 = d2.*t6;
t8 = cos(theta2);
A = reshape([-m1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,-m1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,I1,0.0,t5,-d1.*t3,L1.*t2,-L1.*t3,0.0,0.0,-m2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,-m2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,I2,0.0,0.0,t7,-d2.*t8,-1.0,0.0,0.0,0.0,t5,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,-d1.*t3,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.0,0.0,t2.*t4,t7,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.0,-t3.*t4,-d2.*t8,0.0,0.0,0.0,0.0],[10,10]);
