function M_L = rhsStuffmassMatrixLagrange(I1,I2,L1,d1,d2,m1,m2,theta1,theta2)
%RHSSTUFFMASSMATRIXLAGRANGE
%    M_L = RHSSTUFFMASSMATRIXLAGRANGE(I1,I2,L1,D1,D2,M1,M2,THETA1,THETA2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    22-Oct-2018 22:01:41

t2 = theta1-theta2;
t3 = cos(t2);
t4 = L1.*d2.*m2.*t3;
M_L = reshape([I1+L1.^2.*m2+d1.^2.*m1,t4,t4,I2+d2.^2.*m2],[2,2]);
