function b = rhsStuffbVectorAMB(L1,d1,d2,g,m1,m2,theta1,theta2,theta1dot,theta2dot)
%RHSSTUFFBVECTORAMB
%    B = RHSSTUFFBVECTORAMB(L1,D1,D2,G,M1,M2,THETA1,THETA2,THETA1DOT,THETA2DOT)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    20-Oct-2018 15:08:08

t2 = sin(theta1);
t3 = theta1-theta2;
t4 = sin(t3);
t5 = sin(theta2);
t6 = theta1dot.^2;
b = [d1.*g.*m1.*t2+d2.*g.*m2.*t5+L1.*g.*m2.*t2-L1.*d2.*m2.*t4.*t6+L1.*d2.*m2.*t4.*theta2dot.^2;d2.*m2.*(g.*t5-L1.*t4.*t6)];
