function b_L = rhsstuffbVectorLagrange(L1,d1,d2,g,m1,m2,theta1,theta2,theta1dot,theta2dot)
%RHSSTUFFBVECTORLAGRANGE
%    B_L = RHSSTUFFBVECTORLAGRANGE(L1,D1,D2,G,M1,M2,THETA1,THETA2,THETA1DOT,THETA2DOT)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    22-Oct-2018 22:01:41

t2 = sin(theta1);
t3 = theta1-theta2;
t4 = sin(t3);
b_L = [-d1.*g.*m1.*t2-L1.*g.*m2.*t2-L1.*d2.*m2.*t4.*theta2dot.^2;-d2.*m2.*(g.*sin(theta2)-L1.*t4.*theta1dot.^2)];
