function b = rhsStuffbVectorDAE(L1,d1,d2,g,m1,m2,theta1,theta2,theta1dot,theta2dot)
%RHSSTUFFBVECTORDAE
%    B = RHSSTUFFBVECTORDAE(L1,D1,D2,G,M1,M2,THETA1,THETA2,THETA1DOT,THETA2DOT)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    23-Oct-2018 11:50:30

t2 = theta1dot.^2;
t3 = cos(theta1);
t4 = sin(theta1);
t5 = theta2dot.^2;
b = [-g.*m1;0.0;-g.*m2;0.0;0.0;0.0;-d1.*t2.*t3;-d1.*t2.*t4;-d2.*t5.*cos(theta2)-L1.*t2.*t3;-d2.*t5.*sin(theta2)-L1.*t2.*t4];
